### ISSUE TITLE
QUESTION: Use this to output flamegraphs for all canisters running on mainnet?

### ISSUE THREAD

**Issue by saikatdas0790** [dfinity/canister-profiling#56]
How would one use this to generate regular profiling information for canisters running on the mainnet and written in Rust? Is this at all possible?

**Comment by chenyan-dfinity** [comment]
You can follow the ic-repl script: https://github.com/dfinity/canister-profiling/blob/main/dapps/basic_dao.sh as an example. 

The approach is language agnostic, we can profile any Wasm module targeted at the IC system API. The only restriction is that the canister code cannot access stable memory.
